-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Visitors" add column "leaveParcelAtGate" boolean
--  not null default 'false';
