-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."LocalServiceProviders" add column "isInside" boolean
--  not null default 'false';
