export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SOCIETY_ADMIN: 'SOCIETY_ADMIN',
  SECURITY_GUARD: 'SECURITY_GUARD',
  RESIDENT: 'RESIDENT',
};

export const LOCAL_SERVICE_PROVIDER_LOG_CATEGORIES = {
  LOCAL_SERVICE_PROVIDER_CREATED: 'LOCAL_SERVICE_PROVIDER_CREATED',
  LOCAL_SERVICE_PROVIDER_UPDATED: 'LOCAL_SERVICE_PROVIDER_UPDATED',
  RE_HIRED: 'RE_HIRED',
  HIRED: 'HIRED',
  FIRED: 'FIRED',
  ENTRY: 'ENTRY',
  EXIT: 'EXIT',
  ATTENDANCE: 'ATTENDANCE',
};

export const LOCAL_SERVICE_PROVIDER_ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LEAVE: 'LEAVE',
};

export const LOCAL_SERVICE_PROVIDER_RATING_CATEGORIES = {
  PUNCTUALITY: 'PUNCTUALITY',
  QUALITY: 'QUALITY',
  BEHAVIOUR: 'BEHAVIOUR',
};

export const COMPLAINT_CATEGORIES = {
  PLUMBING: 'PLUMBING',
  ELECTRICAL: 'ELECTRICAL',
};

export const COMPLAINT_SUBCATEGORIES = {
  COMPLAINT: 'COMPLAINT',
  REQUEST: 'REQUEST',
};

export const COMPLAINT_TYPES = {
  PERSONAL: 'PERSONAL',
  COMMUNITY: 'COMMUNITY',
};

export const COMPLAINT_STATUS = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  ON_HOLD: 'ON_HOLD',
  RE_OPENED: 'RE_OPENED',
  RESOLVED: 'RESOLVED',
};

// export const SOS_TYPES = [
//   {
//     id: 'SOS_HEALTH',
//     name: 'HEALTH EMERGENCY',
//     image: 'https://i.imgur.com/O3rmbLL.png',
//   },
//   {
//     id: 'SOS_LIFT',
//     name: 'LIFT EMERGENCY',
//     image: 'https://i.imgur.com/I9mhQbO.png',
//   },
// ];

export const AMENITY_TYPES = {
  DAILY: 'DAILY',
  HOURLY: 'HOURLY',
};

export const VISITOR_VENDOR_TYPES = {
  DELIVERY: 'DELIVERY',
  CAB: 'CAB',
  VISITOR: 'VISITOR',
  VISITING_HELP: 'VISITING_HELP',
};

export const SOS_STATUS = {
  CREATED: 'CREATED',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  RESOLVED: 'RESOLVED',
};

export const REQUEST_VALIDATOR_MODIFICATIONS = {
  UPPERCASE: 'UPPERCASE',
  TRIM: 'TRIM',
};

export const MODIFICATION_TYPES = {
  BEFORE_VALIDATION: 'BEFORE_VALIDATION',
  AFTER_VALIDATION: 'AFTER_VALIDATION',
};

export const USER_ROLES_APPROVAL_STATUS = {
  APPROVED: 'APPROVED',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
};

export const AMENITY_STATUS = {
  BOOKED: 'BOOKED',
  CANCELLED: 'CANCELLED',
};

export const VEHICLE_TYPES = {
  FOUR_WHEELER: 'FOUR_WHEELER',
  TWO_WHEELER: 'TWO_WHEELER',
};

export const VISITOR_STATUS = {
  PRE_APPROVED: 'PRE_APPROVED',
  ALLOWED_ENTRY: 'ALLOWED_ENTRY',
  EXITED: 'EXITED',
  RECEIVED_AT_GATE: 'RECEIVED_AT_GATE',
  COLLECTED: 'COLLECTED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  DENIED: 'DENIED',
};

export const CONSTANTS = {
  userRoles: USER_ROLES,
  localServiceProviderLogCategories: LOCAL_SERVICE_PROVIDER_LOG_CATEGORIES,
  localServiceProviderRatingCategories:
    LOCAL_SERVICE_PROVIDER_RATING_CATEGORIES,
  complaintCategories: COMPLAINT_CATEGORIES,
  complaintSubcategories: COMPLAINT_SUBCATEGORIES,
  complaintTypes: COMPLAINT_TYPES,
  complaintStatus: COMPLAINT_STATUS,
  //   sosTypes: SOS_TYPES,
  amenityTypes: AMENITY_TYPES,
  amenityStatus: AMENITY_STATUS,
  visitorVendorTypes: VISITOR_VENDOR_TYPES,
};
